name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        node: [lts]
        openjdk: [11]
        maven: [3.8.3]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: felixoi/openjdk-maven-node:${{ matrix.openjdk }}-${{ matrix.maven }}-${{ matrix.node }}
          build-args: |
            MAVEN=${{ matrix.maven }}-openjdk-${{ matrix.openjdk }}-slim
            NODE=${{ matrix.node }}
